# Generated by Django 4.1.1 on 2023-06-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_1', models.ImageField(upload_to='premios')),
                ('imagem_2', models.ImageField(blank=True, null=True, upload_to='premios')),
                ('imagem_3', models.ImageField(blank=True, null=True, upload_to='premios')),
                ('imagem_4', models.ImageField(blank=True, null=True, upload_to='premios')),
                ('imagem_5', models.ImageField(blank=True, null=True, upload_to='premios')),
                ('imagem_6', models.ImageField(blank=True, null=True, upload_to='premios')),
                ('pontos', models.IntegerField()),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
    ]
